version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - nginx-network
    volumes:
      - ./docker/nginx/angular/angular.nginx:/etc/nginx/conf.d/default.conf

  react-frontend:
    build:
      context: ./react-frontend
    ports:
      - "8082:80"
    networks:
      - nginx-network
    volumes:
      - ./docker/nginx/react/react.nginx:/etc/nginx/conf.d/default.conf

  proxy:
    build:
      context: ./docker/nginx/proxy
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - react-frontend
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
